##
## see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    commands:
      - |-
        echo "==> install"

  pre_build:
    commands:
      - |-
        echo "==> pre build"

  build:
    commands:
      - |-
        echo "==> build"

  post_build:
    commands:
      - |-
        echo "==> post build"

      - |-
          if [ "x$CI_PR_LEVEL" == "xinit" ]; then
            echo "==> init pull request $CI_PR"
          fi

      - |-
          if [ "x$CI_PR_LEVEL" == "xfree" ]; then
            echo "==> free pull request $CI_PR" && exit -1
          fi

      - |-
          if [ -z "$CI_PR_LEVEL" ]; then
            echo "==> release staging" && exit -1
          fi

      - |-
          if [ ! -z "$CI_REL" ]; then
            echo "==> release $CI_REL" && exit -1
          fi
