##
## see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    commands:
      - |-
        echo "==> install"
      - npm install
      - (cd cloud; npm install)

  pre_build:
    commands:
      - |-
        echo "==> pre build"

  build:
    commands:
      - |-
        echo "==> build"
      - npm run build

  post_build:
    commands:
      - |-
        echo "==> post build"

      - |-
          case $BUILD_LEVEL in
            init)
              (cd cloud; VSN="${BUILD_ISSUE}" cdk deploy)
              ;;
            sync)
              (cd cloud; VSN=${BUILD_ISSUE} cdk deploy)
              ;;
            free)
              (cd cloud; VSN=${BUILD_ISSUE} cdk destroy)
              ;;
            master)
              (cd cloud; VSN=dev cdk deploy)
              ;;
            release)
              (cd cloud; VSN=${BUILD_RELEASE} cdk deploy)
              ;;
          esac
