##
## see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    commands:
      - |-
        echo "==> install"
      - npm install
      - (cd cloud; npm install)

  pre_build:
    commands:
      - |-
        echo "==> pre build"

  build:
    commands:
      - |-
        echo "==> build"
      - npm run build

  post_build:
    commands:
      - |-
        echo "==> post build"

      - |-
          if [ "x$BUILD_LEVEL" == "xfree" ]; then
            (cd cloud; cdk destroy)
          else
            (cd cloud; cdk deploy)
          fi

