##
## see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2


phases:
  install:
    commands:
      - |-
        echo "==> install"

  pre_build:
    commands:
      - |-
        echo "==> pre build"

  build:
    commands:
      - |-
        echo "==> build"

  post_build:
    commands:
      - |-
        echo "==> post build"

      - |-
          if [ "x$BUILD_LEVEL" == "xinit" ]; then
            echo "==> init pull request $BUILD_ISSUE"
          fi

      - |-
          if [ "x$BUILD_LEVEL" == "xfree" ]; then
            echo "==> free pull request $BUILD_ISSUE" && exit -1
          fi

      - |-
          if [ "x$BUILD_LEVEL" == "xmaster" ]; then
            echo "==> release master $BUILD_ISSUE" && exit -1
          fi

      - |-
          if [ "x$BUILD_LEVEL" == "xrelease" ]; then
            echo "==> release $BUILD_RELEASE ($BUILD_COMMIT)" && exit -1
          fi

